// SPDX-License-Identifier: MPL-2.0

import java.util.Properties

plugins {
    alias(libs.plugins.kotlin.multiplatform)
}

// Dev-only server prefill for the tvOS shell, mirroring :shared-ui's
// generateDevServerConfig. Empty for release builds and when the file is absent
// (CI / clean checkout), so developer credentials are never shipped.
val devServerProperties =
    Properties().apply {
        val file = rootProject.file(".local/dev-server.properties")
        if (file.exists()) {
            file.inputStream().use { load(it) }
        }
    }

fun devProperty(key: String): String = devServerProperties.getProperty(key, "")

fun escapeKotlinStringLiteral(value: String): String =
    buildString(value.length) {
        value.forEach { character ->
            when (character) {
                '\\' -> append('\\').append('\\')
                '"' -> append('\\').append('"')
                '$' -> append('\\').append('$')
                '\n' -> append('\\').append('n')
                '\r' -> append('\\').append('r')
                '\t' -> append('\\').append('t')
                else -> append(character)
            }
        }
    }

val generateTvDevServerConfig =
    tasks.register("generateTvDevServerConfig") {
        val outputDir = layout.buildDirectory.dir("generated/tvDevServerConfig/kotlin")
        val serverUrl = devProperty("devServerUrl")
        val username = devProperty("devUsername")
        val password = devProperty("devPassword")
        val xcodeConfiguration = providers.environmentVariable("CONFIGURATION").orElse("Release")
        inputs.property("serverUrl", serverUrl)
        inputs.property("username", username)
        inputs.property("password", password)
        inputs.property("xcodeConfiguration", xcodeConfiguration)
        outputs.dir(outputDir)
        doLast {
            val target = outputDir.get().file("com/jellyscope/tvos/TvDevServerConfig.kt").asFile
            target.parentFile.mkdirs()
            val isDebugBuild = xcodeConfiguration.get().equals("Debug", ignoreCase = true)
            val generatedServerUrl = if (isDebugBuild) serverUrl else ""
            val generatedUsername = if (isDebugBuild) username else ""
            val generatedPassword = if (isDebugBuild) password else ""
            target.writeText(
                """
                |// SPDX-License-Identifier: MPL-2.0
                |// GENERATED by :shared-tvos generateTvDevServerConfig from untracked
                |// .local/dev-server.properties. Empty for release builds and when that file is absent.
                |package com.jellyscope.tvos
                |
                |object TvDevServerConfig {
                |    const val IS_DEBUG_BUILD: Boolean = $isDebugBuild
                |    const val SERVER_URL: String = "${escapeKotlinStringLiteral(generatedServerUrl)}"
                |    const val USERNAME: String = "${escapeKotlinStringLiteral(generatedUsername)}"
                |    const val PASSWORD: String = "${escapeKotlinStringLiteral(generatedPassword)}"
                |}
                |
                """.trimMargin(),
            )
        }
    }

val generateTvDistributionBuildInfo =
    tasks.register("generateTvDistributionBuildInfo") {
        val outputDir = layout.buildDirectory.dir("generated/tvDistributionBuildInfo/kotlin")
        val sourceRevision =
            providers
                .exec {
                    commandLine("git", "rev-parse", "HEAD")
                }.standardOutput
                .asText
                .map(String::trim)
        inputs.property("sourceRevision", sourceRevision)
        outputs.dir(outputDir)
        doLast {
            val target = outputDir.get().file("com/jellyscope/tvos/TvDistributionBuildInfo.kt").asFile
            target.parentFile.mkdirs()
            target.writeText(
                """
                |// SPDX-License-Identifier: MPL-2.0
                |// GENERATED by :shared-tvos:generateTvDistributionBuildInfo.
                |package com.jellyscope.tvos
                |
                |internal object TvDistributionBuildInfo {
                |    const val SOURCE_REVISION: String = "${sourceRevision.get()}"
                |}
                |
                """.trimMargin(),
            )
        }
    }

tasks.register("verifyDevServerLiteralEscaping") {
    doLast {
        val value = "slash\\quote\"dollar${'$'}line\r\n雪"
        check(escapeKotlinStringLiteral(value) == "slash\\\\quote\\\"dollar\\${'$'}line\\r\\n雪") {
            "Kotlin tvOS dev-server escaping changed"
        }
    }
}

kotlin {
    jvmToolchain(
        libs.versions.jdkToolchain
            .get()
            .toInt(),
    )

    tvosArm64 {
        binaries.framework {
            baseName = "SharedTv"
            isStatic = true
            export(project(":shared-core"))
        }
    }

    tvosSimulatorArm64 {
        binaries.framework {
            baseName = "SharedTv"
            isStatic = true
            export(project(":shared-core"))
        }
    }

    // JVM target exists solely so commonTest presenter suites run fast on the
    // host, matching the project's JVM-first unit test strategy.
    jvm()

    sourceSets {
        commonMain {
            kotlin.srcDir(generateTvDevServerConfig)
            kotlin.srcDir(generateTvDistributionBuildInfo)
        }
        commonMain.dependencies {
            api(project(":shared-core"))
            implementation(libs.kotlinx.coroutines.core)
        }

        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
        }
    }
}
