// SPDX-License-Identifier: MPL-2.0

import java.io.File
import java.util.Properties

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kotlin.multiplatform.library)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.kotlin.plugin.compose)
}

// Dev-only server prefill sourced from untracked .local/dev-server.properties, mirroring
// the Android BuildConfig prefill but for the KMP (iOS/desktop) targets that lack BuildConfig.
// Generates empty strings for release builds and when the file is absent (CI /
// clean checkout), so developer credentials are never shipped.
val devServerProperties =
    Properties().apply {
        val file = rootProject.file(".local/dev-server.properties")
        if (file.exists()) {
            file.inputStream().use { load(it) }
        }
    }

fun devProperty(key: String): String = devServerProperties.getProperty(key, "")

fun escapeKotlinStringLiteral(value: String): String =
    buildString(value.length) {
        value.forEach { character ->
            when (character) {
                '\\' -> append('\\').append('\\')
                '"' -> append('\\').append('"')
                '$' -> append('\\').append('$')
                '\n' -> append('\\').append('n')
                '\r' -> append('\\').append('r')
                '\t' -> append('\\').append('t')
                else -> append(character)
            }
        }
    }

fun writeDevServerConfig(
    target: File,
    configuration: String,
    serverUrl: String,
    username: String,
    password: String,
) {
    target.parentFile.mkdirs()
    val isDebugBuild = configuration.equals("Debug", ignoreCase = true)
    val generatedServerUrl = if (isDebugBuild) serverUrl else ""
    val generatedUsername = if (isDebugBuild) username else ""
    val generatedPassword = if (isDebugBuild) password else ""
    target.writeText(
        """
        |// SPDX-License-Identifier: MPL-2.0
        |// GENERATED by :shared-ui generateDevServerConfig from untracked
        |// .local/dev-server.properties. Empty for release builds and when that file is absent.
        |package com.jellyscope.ui
        |
        |internal object DevServerConfig {
        |    const val SERVER_URL: String = "${escapeKotlinStringLiteral(generatedServerUrl)}"
        |    const val USERNAME: String = "${escapeKotlinStringLiteral(generatedUsername)}"
        |    const val PASSWORD: String = "${escapeKotlinStringLiteral(generatedPassword)}"
        |    const val IS_DEBUG_BUILD: Boolean = $isDebugBuild
        |}
        |
        """.trimMargin(),
    )
}

val generateDevServerConfig =
    tasks.register("generateDevServerConfig") {
        val outputDir = layout.buildDirectory.dir("generated/devServerConfig/kotlin")
        val serverUrl = devProperty("devServerUrl")
        val username = devProperty("devUsername")
        val password = devProperty("devPassword")
        val xcodeConfiguration = providers.environmentVariable("CONFIGURATION").orElse("Release")
        inputs.property("serverUrl", serverUrl)
        inputs.property("username", username)
        inputs.property("password", password)
        inputs.property("xcodeConfiguration", xcodeConfiguration)
        outputs.dir(outputDir)
        doLast {
            val target = outputDir.get().file("com/jellyscope/ui/DevServerConfig.kt").asFile
            writeDevServerConfig(
                target = target,
                configuration = xcodeConfiguration.get(),
                serverUrl = serverUrl,
                username = username,
                password = password,
            )
        }
    }

val generateDistributionBuildInfo =
    tasks.register("generateDistributionBuildInfo") {
        val outputDir = layout.buildDirectory.dir("generated/distributionBuildInfo/kotlin")
        val sourceRevision =
            providers
                .exec {
                    commandLine("git", "rev-parse", "HEAD")
                }.standardOutput
                .asText
                .map(String::trim)
        inputs.property("sourceRevision", sourceRevision)
        outputs.dir(outputDir)
        doLast {
            val target = outputDir.get().file("com/jellyscope/ui/DistributionBuildInfo.kt").asFile
            target.parentFile.mkdirs()
            target.writeText(
                """
                |// SPDX-License-Identifier: MPL-2.0
                |// GENERATED by :shared-ui:generateDistributionBuildInfo.
                |package com.jellyscope.ui
                |
                |internal object DistributionBuildInfo {
                |    const val SOURCE_REVISION: String = "${sourceRevision.get()}"
                |}
                |
                """.trimMargin(),
            )
        }
    }

val verifyReleaseDevServerConfig =
    tasks.register("verifyReleaseDevServerConfig") {
        group = "verification"
        description = "Verifies that iOS Release dev-server config cannot contain developer credentials."
        val outputDir = layout.buildDirectory.dir("verification/devServerConfig")
        outputs.dir(outputDir)
        doLast {
            val sentinelServerUrl = "https://sentinel.invalid\\path\"${'$'}server\r\n雪"
            val sentinelUsername = "sentinel-${'$'}user"
            val sentinelPassword = "sentinel-password\t雪"
            val releaseTarget = outputDir.get().file("release/DevServerConfig.kt").asFile
            val debugTarget = outputDir.get().file("debug/DevServerConfig.kt").asFile

            writeDevServerConfig(
                target = releaseTarget,
                configuration = "Release",
                serverUrl = sentinelServerUrl,
                username = sentinelUsername,
                password = sentinelPassword,
            )
            writeDevServerConfig(
                target = debugTarget,
                configuration = "Debug",
                serverUrl = sentinelServerUrl,
                username = sentinelUsername,
                password = sentinelPassword,
            )

            val releaseSource = releaseTarget.readText()
            val debugSource = debugTarget.readText()

            fun credentialValues(
                source: String,
                field: String,
            ): List<String> =
                Regex("""const val $field: String = \"([^\"]*)\"""")
                    .findAll(source)
                    .map { match -> match.groupValues[1] }
                    .toList()

            check(sentinelServerUrl !in releaseSource) { "Release SERVER_URL verification failed" }
            check(sentinelUsername !in releaseSource) { "Release USERNAME verification failed" }
            check(sentinelPassword !in releaseSource) { "Release PASSWORD verification failed" }
            listOf("SERVER_URL", "USERNAME", "PASSWORD").forEach { field ->
                check(credentialValues(releaseSource, field) == listOf("")) {
                    "Release $field emptiness verification failed"
                }
            }
            check("const val IS_DEBUG_BUILD: Boolean = false" in releaseSource) {
                "Release IS_DEBUG_BUILD verification failed"
            }
            check("const val SERVER_URL: String = \"${escapeKotlinStringLiteral(sentinelServerUrl)}\"" in debugSource) {
                "Debug SERVER_URL escaping verification failed"
            }
            check("const val USERNAME: String = \"${escapeKotlinStringLiteral(sentinelUsername)}\"" in debugSource) {
                "Debug USERNAME escaping verification failed"
            }
            check("const val PASSWORD: String = \"${escapeKotlinStringLiteral(sentinelPassword)}\"" in debugSource) {
                "Debug PASSWORD escaping verification failed"
            }
            check("const val IS_DEBUG_BUILD: Boolean = true" in debugSource) {
                "Debug IS_DEBUG_BUILD verification failed"
            }
        }
    }

kotlin {
    jvmToolchain(
        libs.versions.jdkToolchain
            .get()
            .toInt(),
    )

    android {
        namespace = "com.jellyscope.ui"
        compileSdk =
            libs.versions.compileSdk
                .get()
                .toInt()
        minSdk =
            libs.versions.minSdk
                .get()
                .toInt()

        // Compose MP resources need Android resources enabled under the
        // com.android.kotlin.multiplatform.library plugin (off by default);
        // without this the .cvr assets never reach the APK and string
        // lookups crash at runtime.
        experimentalProperties["android.experimental.kmp.enableAndroidResources"] = true

        withHostTest {}
    }

    iosArm64 {
        binaries.framework {
            baseName = "SharedUi"
            isStatic = true
        }
    }

    iosSimulatorArm64 {
        binaries.framework {
            baseName = "SharedUi"
            isStatic = true
        }
    }

    jvm()

    sourceSets {
        commonMain {
            kotlin.srcDir(generateDevServerConfig)
            kotlin.srcDir(generateDistributionBuildInfo)
        }
        commonMain.dependencies {
            api(project(":shared-core"))
            api(compose.runtime)
            implementation(compose.components.resources)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.materialIconsExtended)
            implementation(compose.ui)
            implementation(libs.jetbrains.lifecycle.viewmodel.compose)
            implementation(libs.jetbrains.lifecycle.runtime.compose)
            implementation(libs.jetbrains.navigation.compose)
            implementation(libs.jetbrains.ui.backhandler)
            implementation(libs.koin.compose.viewmodel)
            implementation(libs.atomicfu)
            implementation(libs.coil.compose)
            implementation(libs.coil.network.ktor3)
        }

        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
        }

        androidMain.dependencies {
            implementation(compose.preview)
            // ui-tooling (ComposeViewAdapter) must be on the module classpath for
            // Android Studio to render @Preview composables defined in this module.
            // The KMP android-library plugin has no debug/release variant split, so
            // this cannot be debug-scoped here.
            implementation(compose.uiTooling)
            implementation(libs.media3.exoplayer)
            implementation(libs.media3.ui)
            implementation(libs.androidx.palette.ktx)
        }

        jvmMain.dependencies {
            implementation(compose.desktop.common)
            implementation(libs.jna)
        }

        jvmTest.dependencies {
            implementation(libs.kotlin.test)
        }
    }
}

compose.resources {
    packageOfResClass = "com.jellyscope.ui.generated.resources"
    // Public so android-tv-app can reuse shared string resources (e.g. the
    // media-info labels) instead of duplicating them into TV's own strings.xml.
    publicResClass = true
}
