// SPDX-License-Identifier: MPL-2.0

package com.jellyscope.core.util

/**
 * Closed stable operation vocabulary for shared repository diagnostics.
 * Values are wire tokens and must not contain request, account, or server data.
 */
enum class DiagnosticOperation(
    val wireValue: String,
) {
    UploadClientLogs("uploadClientLogs"),
    GetLibraries("getLibraries"),
    GetKidsCatalogue("getKidsCatalogue"),
    GetContinueWatching("getContinueWatching"),
    GetNextUp("getNextUp"),
    GetItemDetail("getItemDetail"),
    GetRelated("getRelated"),
    GetRelatedGroups("getRelatedGroups"),
    GetSeasons("getSeasons"),
    GetEpisodes("getEpisodes"),
    GetRecentlyAdded("getRecentlyAdded"),
    GetUpcomingEpisodes("getUpcomingEpisodes"),
    GetLibraryItems("getLibraryItems"),
    GetLibraryShuffleQueue("getLibraryShuffleQueue"),
    GetItemsByIds("getItemsByIds"),
    GetGenres("getGenres"),
    GetStudios("getStudios"),
    GetLibraryFilters("getLibraryFilters"),
    GetLibraryRecommendationSection("getLibraryRecommendationSection"),
    GetMediaSegments("getMediaSegments"),
    GetCollections("getCollections"),
    GetCollectionItems("getCollectionItems"),
    GetGenreItems("getGenreItems"),
    GetStudioItems("getStudioItems"),
    GetPerson("getPerson"),
    GetPersonItems("getPersonItems"),
    GetPersonItemsPage("getPersonItemsPage"),
    GetSuggestions("getSuggestions"),
    GetRibbonItems("getRibbonItems"),
    GetFavorites("getFavorites"),
    Search("search"),
    FindPersons("findPersons"),
    GetPlaybackInfo("getPlaybackInfo"),
    SetPlayed("setPlayed"),
    SetFavorite("setFavorite"),
    PreviousRunFailure("previousRunFailure"),
    GetLogCollectionState("getLogCollectionState"),
    SetLogCollectionEnabled("setLogCollectionEnabled"),
    SendClientLogs("sendClientLogs"),
    GetPlaybackPreferences("getPlaybackPreferences"),
    SavePlaybackPreferences("savePlaybackPreferences"),
    SavePlayerDeviceSettings("savePlayerDeviceSettings"),
    GetPlayerDevicePolicy("getPlayerDevicePolicy"),
    RefreshPlayerDevicePolicy("refreshPlayerDevicePolicy"),
    GetAvailablePlayerBackends("getAvailablePlayerBackends"),
    GetOpenSubtitlesApiKey("getOpenSubtitlesApiKey"),
    SetOpenSubtitlesApiKey("setOpenSubtitlesApiKey"),
    GetOpenSubtitleResultPreference("getOpenSubtitleResultPreference"),
    SetOpenSubtitleResultPreference("setOpenSubtitleResultPreference"),
    SetAppTheme("setAppTheme"),
    SetPictureInPictureEnabled("setPictureInPictureEnabled"),
    SetTileSize("setTileSize"),
    SetRememberLastLibraryView("setRememberLastLibraryView"),
    ClearLocalSubtitles("clearLocalSubtitles"),
    SetVerboseLogcatEnabled("setVerboseLogcatEnabled"),
    SetPlaybackInfoAtStartEnabled("setPlaybackInfoAtStartEnabled"),
    GetDownloadUsage("getDownloadUsage"),
    GetDownloadSettings("getDownloadSettings"),
    GetDownloadRemovalPreview("getDownloadRemovalPreview"),
    AuthorizeDownloadRemoval("authorizeDownloadRemoval"),
    ReleaseDownloadRemovalPreview("releaseDownloadRemovalPreview"),
    Logout("logout"),
    AuthValidateServer("authValidateServer"),
    AuthLogin("authLogin"),
    AuthQuickConnect("authQuickConnect"),
    AuthSignOut("authSignOut"),
    AuthLogout("authLogout"),
    RefreshParentalRating("refreshParentalRating"),
    OpenSubtitleSearch("openSubtitleSearch"),
    OpenSubtitleDownload("openSubtitleDownload"),
    GetSubtitleSelections("getSubtitleSelections"),
    LocalSubtitleRead("localSubtitleRead"),
    LocalSubtitleUpload("localSubtitleUpload"),
    LocalSubtitleRefresh("localSubtitleRefresh"),
    LocalSubtitleFetch("localSubtitleFetch"),
    WatchNextSync("watchNextSync"),
    DownloadObserve("downloadObserve"),
    DownloadLoad("downloadLoad"),
    DownloadQuota("downloadQuota"),
    DownloadPause("downloadPause"),
    DownloadResume("downloadResume"),
    DownloadResumeAll("downloadResumeAll"),
    DownloadRetry("downloadRetry"),
    DownloadSchedulingWake("downloadSchedulingWake"),
    DownloadCancel("downloadCancel"),
    DownloadDelete("downloadDelete"),
    DownloadLease("downloadLease"),
    GetRecentSearches("getRecentSearches"),
    AddRecentSearch("addRecentSearch"),
    ClearRecentSearches("clearRecentSearches"),
    AmbientColorExtraction("ambientColorExtraction"),
    ;

    /** Alias used by callers that name fields by their serialized wire value. */
    val diagnosticValue: String
        get() = wireValue
}
